# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: winform
      MONGO_INITDB_ROOT_PASSWORD: winform123
      MONGO_INITDB_DATABASE: winform
    ports:
      - '27017-27019:27017-27019'
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: winform
      ME_CONFIG_MONGODB_ADMINPASSWORD: winform123
      ME_CONFIG_MONGODB_URL: mongodb://winform:winform123@mongo:27017/
